services:
  tor_proxy:
    image: getumbrel/tor:0.4.7.8
    container_name: tor_proxy
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ./tor/torrc-proxy:/etc/tor/torrc:ro
      - ./tor/data:/data
    ports:
      - "127.0.0.1:${TOR_PROXY_PORT}:${TOR_PROXY_PORT}"
    environment:
      HOME: "/tmp"
    networks:
      umbrel:
        ipv4_address: ${TOR_PROXY_IP}

  nginx:
    image: nginx:1.17.8
    container_name: nginx
    depends_on: [dashboard, manager]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: on-failure
    ports:
      - "${NGINX_PORT}:80"
    networks:
      umbrel:
        ipv4_address: ${NGINX_IP}

  dashboard:
    image: getumbrel/dashboard:0.5.4
    container_name: dashboard
    restart: on-failure
    networks:
      umbrel:
        ipv4_address: ${DASHBOARD_IP}

  manager:
    image: getumbrel/manager:0.5.4
    container_name: manager
    restart: on-failure
    volumes:
      - ./info.json:/info.json
      - ./db:/db
      - ./jwt:/jwt
      - ./events/signals:/signals
      - ./app-data:/app-data
      - ./repos:/repos
      - ./statuses:/statuses
      - ./tor/data:/var/lib/tor
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_BINARY:-/usr/bin/docker}:/usr/bin/docker
    environment:
      PORT: "3006"
      USER_PASSWORD_FILE: "/db/user.json"
      JWT_PUBLIC_KEY_FILE: "/jwt/jwt.pem"
      JWT_PRIVATE_KEY_FILE: "/jwt/jwt.key"
      JWT_EXPIRATION: "604800"
      DOCKER_COMPOSE_DIRECTORY: "/umbrel"
      UMBREL_SEED_FILE: "/db/umbrel-seed/seed"
      UMBREL_DASHBOARD_HIDDEN_SERVICE_FILE: "/var/lib/tor/web/hostname"
      UMBREL_AUTH_SECRET: ${UMBREL_AUTH_SECRET}
      BITCOIN_P2P_HIDDEN_SERVICE_FILE: "/var/lib/tor/bitcoin-p2p/hostname"
      BITCOIN_P2P_PORT: ${BITCOIN_P2P_PORT}
      BITCOIN_RPC_HIDDEN_SERVICE_FILE: "/var/lib/tor/bitcoin-rpc/hostname"
      BITCOIN_RPC_PORT: ${BITCOIN_RPC_PORT}
      BITCOIN_RPC_USER: ${BITCOIN_RPC_USER}
      BITCOIN_RPC_PASSWORD: ${BITCOIN_RPC_PASS}
      LND_REST_HIDDEN_SERVICE_FILE: "/var/lib/tor/lnd-rest/hostname"
      LND_GRPC_HIDDEN_SERVICE_FILE: "/var/lib/tor/lnd-grpc/hostname"
      LND_CERT_FILE: "/lnd/tls.cert"
      LND_ADMIN_MACAROON_FILE: "/lnd/data/chain/bitcoin/${BITCOIN_NETWORK}/admin.macaroon"
      SHUTDOWN_SIGNAL_FILE: "/signals/shutdown"
      REBOOT_SIGNAL_FILE: "/signals/reboot"
      GITHUB_REPO: "getumbrel/umbrel"
      UMBREL_VERSION_FILE: "/info.json"
      UPDATE_STATUS_FILE: "/statuses/update-status.json"
      UPDATE_SIGNAL_FILE: "/signals/update"
      UPDATE_LOCK_FILE: "/statuses/update-in-progress"
      BACKUP_STATUS_FILE: "/statuses/backup-status.json"
      DEBUG_STATUS_FILE: "/statuses/debug-status.json"
      REPO_UPDATE_STATUS_FILE: "/statuses/repo-update-status.json"
      TOR_HIDDEN_SERVICE_DIR: "/var/lib/tor"
      IS_UMBREL_OS: ${IS_UMBREL_OS:-"false"}
      UMBREL_APP_REPO_URL: "https://github.com/getumbrel/umbrel-apps.git"
    networks:
      umbrel:
        ipv4_address: ${MANAGER_IP}

  auth:
    image: getumbrel/auth-server:v0.5.1
    container_name: auth
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ./tor/data:/var/lib/tor:ro
      - ./app-data:/app-data:ro
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    environment:
      PORT: ${AUTH_PORT}
      UMBREL_AUTH_SECRET: ${UMBREL_AUTH_SECRET}
      MANAGER_IP: ${MANAGER_IP}
      MANAGER_PORT: 3006
      DASHBOARD_IP: ${DASHBOARD_IP}
      DASHBOARD_PORT: 3004
    networks:
      umbrel:
        ipv4_address: ${AUTH_IP}

networks:
  umbrel:
    name: umbrel_main_network
    ipam:
      driver: default
      config:
        - subnet: "${NETWORK_IP}/16"
