name: Node.js CI

on: push

jobs:
  umbreld:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: packages/umbreld
    strategy:
      fail-fast: false
      matrix:
        task:
          - format:check
          # - lint
          - typecheck
          - test:unit -- --coverage --watch=false
          - test:integration -- --coverage --watch=false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          sudo apt-get install -y imagemagick
          sudo npm clean-install
      - run: sudo npm run ${{ matrix.task }}
  ui:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: packages/ui
    strategy:
      fail-fast: false
      matrix:
        task:
          - format:check
          - typecheck
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Install Umbreld dependencies
        if: ${{ matrix.task == 'typecheck' }}
        run: npm --prefix ../umbreld clean-install
      - name: Install dependencies
        run: pnpm install
      - run: pnpm run ${{ matrix.task }}
